### ISSUE TITLE
easykey error in markdown

### ISSUE THREAD

**Issue by mclearc** [egh/zotxt-emacs#9]
Zotxt works great with org-mode for me, but I keep getting an easykey error when I select an item from the minibuffer for citing. I consistently get `REQUEST [error] Error (error) while connecting to http://127.0.0.1:23119/zotxt/items.`. I think this may be due to duplicates, as discussed in #22. But it could also be something with diacritics or apostrophes in titles. Any help would be appreciated – it's a great tool!

Relatedly, is there any prospect for control over the nature of zotxt's easycitekey format? I'd love for it to just use the citekeys from betterbibtex.

**Comment by egh** [comment]
@mclearc I agree completely that Better BibTeX provides a better solution for keys. It should be possible to use it by setting `org-zotxt-link-description-style` to `:betterbibtexkey`.

I'm thinking I should probably deprecate easykeys. It was an okay idea, but seems to cause a lot of problem, and Better BibTeX has solved them well.

**Comment by egh** [comment]
@mclearc I realized I never responded to your issue. It's hard to know where the issue could be coming from. But if you can enable debug logging in zotero (https://www.zotero.org/support/preferences/hidden_preferences) and start firefox/zotero from the command line (on mac or linux - not sure how to do this on windows), and then run the command that errors, you can then copy and paste the error into this ticket so I can know what the issue is. Thanks, and thanks for the report!

**Comment by mclearc** [comment]
I've gone back to using helm-bibtex for citations, but this is very helpful when writing notes in org!

**Comment by egh** [comment]
Great! Let me know if you encounter other issues. Thanks.
